# Config file for automatic testing at travis-ci.org

dist: focal
sudo: required
language: python
python: 3.8

env:
  - TOX_ENV=py38-django31

matrix:
  fast_finish: true

install: pip install -r requirements-test.txt

script: tox -e $TOX_ENV
